- name: create ec2 and route53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-04097b4e3c38bb38c
    zone_id: Z07155921YL2PZLNGBCDC
    domain: vinaymukkamalla.fun
    instances:
    - mongodb

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print ec2_output file
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

