- name: create ec2 and route53
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-04097b4e3c38bb38c
    zone_id: Z07155921YL2PZLNGBCDC
    domain: vinaymukkamalla.fun
    # instances:
    # - rabbitmq

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: print ec2_output file
    ansible.builtin.debug:
      msg: "{{ ec2_output }}"

  # - name: print public ip    # we have checked and it is working
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  # - name: print private ip
  #   ansible.builtin.debug:
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"


  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ item.item }}.{{ domain }}"
      type: A 
      ttl: 60
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

  - name: create route53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain }}"
      record: "{{ domain }}"
      type: A 
      ttl: 60
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"


